### ISSUE TITLE
Show the bitrate of each station

### ISSUE THREAD

**Issue by etix** [elthariel/icast#30]
... and be able to view/play all the bitrates supported by the given station. Maybe allow filtering by bitrates too.

**Comment by elthariel** [comment]
Thank you very much for the feature suggestion.

I'll handle the display of the bitrate today. The filtering will be a separate issue (linked)

**Comment by elthariel** [comment]
Done in 8726b12beaf2d8ed3e12cd76ce5a95c9afc2020e
